### ISSUE TITLE
Ingress overwrites instead of adds X-Forwarded-* headers

### ISSUE THREAD

**Issue by ractive** [kubernetes/contrib#2312]
The ingress proxy sets the X-Forwarded-* headers and hereby overwrites previous values set by other proxies. So the application only sees the X-Forwarded-* header values set by the ingress, but not by the first proxy and can therefore not create URLs pointing to itself. The ingress proxy should either add these headers (using `add_header`) or add its value in a comma separated list to an existing header value. Unfortunately there's no standard describing these X-Forwarded headers, but it seems as if both variants (multiple headers and comma separated values) are seen in the wild.
The changes would be probably needed to be done here: https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/nginx.tmpl#L276

We concretely face this issue because we terminate all https connections on an external loadbalancer (e.g. https://api.example.com) that then routes the traffic via http to an ingress endpoint (e.g. http://internal.example.com). The redirect URI that is created by the internal app is now https://api.example.com:80 - which is wrong. This is because the ingress sets the X-Forwarded-Port header to 80. The X-Forwarded-Port value 443 which is set by the loadbalancer (where ssl is terminated) should be preserved.

This issue shows up in a Spring Boot application with OAuth2 protected resources, where the  app creates the redirect_uri pointing to itself sent to the OAuth provider using a UriComponentsBuilder [1] in the OAuth2ClientContextFilter [2]. The UriComponentsBuilder builds the URL using the X-Forwarded-* headers, picking the first header and the first value (if comma spearated).

[1] https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/util/UriComponentsBuilder.java#L705

[2] https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/client/filter/OAuth2ClientContextFilter.java#L122

**Comment by aledbf** [comment]
@ractive thanks for the report. Please check this https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/nginx.tmpl#L110
I will add the same logic (pass the value if the header exists or add a default) in:

- `X-Forwarded-Host`
- `X-Forwarded-Port`
- `X-Forwarded-Proto`

**Comment by aledbf** [comment]
@ractive sorry but this is already fixed in the new version. Please check https://github.com/kubernetes/ingress/blob/master/controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl#L110

**Comment by ractive** [comment]
Ah ok. So I looked in the wrong nginx.tmpl file. Is this already part of a released version?

**Comment by aledbf** [comment]
@ractive not yet, next week.

**Comment by ractive** [comment]
Great! We're looking forward to this release!
Thanks.

**Comment by ractive** [comment]
We still have this issue. We're using this server version:

Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4+coreos.0", GitCommit:"97c11b097b1a2b194f1eddca8ce5468fcc83331c", GitTreeState:"clean", BuildDate:"2017-03-08T23:54:21Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

Do we need to somehow update the current ingress instances to use the updated template?

**Comment by alikhan-io** [comment]
+1 on this. Has this been resolved to anyones knowledge?

**Comment by yveszoundi** [comment]
@aledbf , are there any updates for this issue?

After couple of rather long investigations, I found this page. I have exactly the same problem for an application using Java libraries (_spring boot_ + _spring oauth2_) deployed into Kubernetes (_ingress-nginx_). 

@ractive, did you managed to work around that issue, in a "non-radical" way?

**Comment by yveszoundi** [comment]
@ractive, I found a rather _intrusive workaround_ per code/configuration below, it was a rather painful exercise, if it solves your problems too, you owe me beer :-) !
@aledbf , is there something that I'm missing that could reduce complexity that is obvious to you?

**A) Ingress side work**
```yaml
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For, X-Forwarded-Proto, X-Forwarded-Port, X-Forwarded-Prefix"    
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Request-Id: $request_id";
      more_set_headers "X-Forwarded-Host: $host";
      more_set_headers "X-Forwarded-Proto: $scheme";
      more_set_headers "X-Forwarded-For: $proxy_add_x_forwarded_for";
      proxy_set_header X-Forwarded-Prefix "/secureapp/app";
      #doesnotwork proxy_cookie_path /app /secureapp/app;

  path: /secureapp
```
**B) Java side work**

a) Use the _X-forwarded-_ headers in Tomcat (Spring oauth2 application)

We want to force Java to pick up _x-forwarded-host_, _x-forwarded-proto_ and _x-forwarded-prefix_.

```java
@Bean
public FilterRegistrationBean forwardHeadersFilterBean() {
   FilterRegistrationBean bean = new FilterRegistrationBean(new ForwardedHeaderFilter());
   bean.setOrder(Ordered.HIGHEST_PRECEDENCE);
   return bean;
 }
```

b) Prepend the ingress location to the application cookie path

By default to the application cookie path is "/app", we want it to be "/secureapp/app" inside Kubernetes.

```java
// At the ingress level, proxy_cookie_path doesn't seem to work for me
@Bean
public ServletContextInitializer servletContextInitializer() {
  return new ServletContextInitializer() {

     @Override
     public void onStartup(ServletContext servletContext) throws ServletException {
       SessionCookieConfig sessionCookieConfig = servletContext.getSessionCookieConfig();
       sessionCookieConfig.setPath("/secureapp/app");
     }
  };
}
```

**Comment by ractive** [comment]
To do a quick fix we called the internal service on kubernetes also via https routed through our loadbalancer that terminates SSL. So honestly I did not follow this any further. Isn't this fixed as stated in https://github.com/kubernetes/contrib/issues/2312#issuecomment-273670672 ?

**Comment by SEJeff** [comment]
@ractive does your external load balancer support the [PROXY protocol](https://www.haproxy.com/blog/haproxy/proxy-protocol/)? haproxy, nginx, amazon, and google's load balancers all support it. It will mitigate this problem for you entirely (and is generally a better / protocol agnostic way of preserving source ip).

**Comment by ractive** [comment]
Unfortunately not, no. :-/

**Comment by ryandawsonuk** [comment]
Another way to set x-forwarded-prefix is https://github.com/kubernetes/ingress-nginx/pull/1805#issuecomment-366711616
